:scheduler:
  :schedule:
    check_health_job:
      every: '15m'
      class: Scheduled::CheckHealthJob
    fetch_metrics_job:
      every: '15m'
      class: Scheduled::FetchMetricsJob
    flush_metrics_job:
      every: '1d'
      class: Scheduled::FlushMetricsJob
    cancel_hanging_builds_job:
      every: '1m'
      class: Scheduled::CancelHangingBuildsJob
    check_cluster_status_job:
      every: '30s'
      class: Scheduled::CheckClusterStatusJob